---
abstract: 'IO::All of it to Graham and Damian!'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: IO::All
name: IO-All
no_index:
  directory:
    - inc
    - t
recommends:
  File::ReadBackwards: 0
requires:
  IO::String: 1.08
  perl: 5.6.1
resources:
  homepage: http://github.com/ingydotnet/io-all-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/io-all-pm.git
version: 0.42
